project:
  type: website
  output-dir: .

website:
  title: "Decision Making with Sentiment Analysis in R"
  navbar:
    left:
      - href: index.html
        text: "Home"
      - href: index.pdf
        text: "Handout PDF"
      - href: presentation.html
        text: "Presentation"
      - href: presentation.pdf
        text: "Presentation PDF"
      - href: Exercises.zip
        text: "Exercises"

format:
  html:
    theme: cosmo
    embed-resources: true
    toc: true
